name: Maven Verify

permissions: { }

on:
  push:
    branches-ignore:
      - main
  pull_request:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Verify
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ 25 ]
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
          cache: "maven"
      - name: Start Mock Server
        run: |
          cd test/mock-server
          nohup ../../mvnw -B -DskipTests spring-boot:run > mock-server.log 2>&1 &
          echo $! > mock-server.pid
          sleep 10
      - name: Build and Test
        run: |
          ./mvnw clean verify -P integration-test --batch-mode --update-snapshots
      - name: Stop Mock Server
        run: |
          cd test/mock-server
          kill "$(cat mock-server.pid)" || true
          rm mock-server.pid || true
      - name: Test Reproducibility
        run: |
          ./mvnw clean install -DskipTests --batch-mode
          ./mvnw clean verify artifact:compare -DskipTests --batch-mode
