name: Build and Publish Site
on:
  workflow_call:
  workflow_dispatch:

permissions: { }

jobs:
  publish-site:
    runs-on: ubuntu-latest
    steps:
      - name: Install lftp
        run: sudo apt install -y lftp

      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Read commit time
        id: commit_time
        run: |
          COMMIT_TIME=$(git log -1 --format=%cI)
          echo "COMMIT_TIME=$COMMIT_TIME"
          echo "COMMIT_TIME=$COMMIT_TIME" >> $GITHUB_OUTPUT

      - name: Get Project Version
        id: project_version
        run: |
          PROJECT_VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
          # if the version ends with -SNAPSHOT, set it to "snapshot"
          if [[ "$PROJECT_VERSION" == *"-SNAPSHOT" ]]; then
            PROJECT_VERSION="snapshot"
          fi
          echo "Project Version: $PROJECT_VERSION"
          echo "PROJECT_VERSION=$PROJECT_VERSION" >> $GITHUB_OUTPUT

      - name: Set up JDK 25
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          java-version: "25"
          distribution: 'temurin'
          cache: "maven"

      - name: Build and generate Site
        run: ./mvnw clean install site site:stage -DskipTests -Dproject.build.outputTimestamp=${{ steps.commit_time.outputs.COMMIT_TIME }}

      - name: Publish Site via FTP
        run: |
          lftp -u "${{ secrets.FTP_USER }}","${{ secrets.FTP_SECRET }}" "${{ secrets.FTP_HOST }}" <<EOF
          mirror --reverse --verbose --delete --parallel=8 "target/staging/" "/${{ steps.project_version.outputs.PROJECT_VERSION }}/site/"
          quit
          EOF
